services:
  email-api:
    image: ghcr.io/mikayil-dev/email-api:latest
    container_name: email-api
    restart: unless-stopped
    ports:
      - "3411:3000"
    environment:
      - PORT=3000
      - CONFIG_FILE=/config/origins.json
    volumes:
      - ./origins.json:/config/origins.json:ro
